"""empty message

Revision ID: 602f0d5b30a9
Revises: c9e5ae004c0f
Create Date: 2024-05-02 01:34:06.980045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602f0d5b30a9'
down_revision = 'c9e5ae004c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('patronimic', sa.String(length=128), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('working_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='fk_department_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_hire_date'), ['hire_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_patronimic'), ['patronimic'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_salary'), ['salary'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_working_status'), ['working_status'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_department_id')
        batch_op.drop_index('ix_user_first_name')
        batch_op.drop_index('ix_user_hire_date')
        batch_op.drop_index('ix_user_last_name')
        batch_op.drop_index('ix_user_patronimic')
        batch_op.drop_index('ix_user_salary')
        batch_op.drop_index('ix_user_working_status')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('patronimic', sa.VARCHAR(length=128), nullable=True),
    sa.Column('salary', sa.INTEGER(), nullable=True),
    sa.Column('hire_date', sa.DATETIME(), nullable=True),
    sa.Column('working_status', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='fk_department_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_working_status', ['working_status'], unique=False)
        batch_op.create_index('ix_user_salary', ['salary'], unique=False)
        batch_op.create_index('ix_user_patronimic', ['patronimic'], unique=False)
        batch_op.create_index('ix_user_last_name', ['last_name'], unique=False)
        batch_op.create_index('ix_user_hire_date', ['hire_date'], unique=False)
        batch_op.create_index('ix_user_first_name', ['first_name'], unique=False)
        batch_op.create_index('ix_user_department_id', ['department_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_working_status'))
        batch_op.drop_index(batch_op.f('ix_employees_salary'))
        batch_op.drop_index(batch_op.f('ix_employees_patronimic'))
        batch_op.drop_index(batch_op.f('ix_employees_last_name'))
        batch_op.drop_index(batch_op.f('ix_employees_hire_date'))
        batch_op.drop_index(batch_op.f('ix_employees_first_name'))
        batch_op.drop_index(batch_op.f('ix_employees_department_id'))

    op.drop_table('employees')
    # ### end Alembic commands ###
