"""empty message

Revision ID: 9235279319bf
Revises: 
Create Date: 2024-06-25 13:12:59.725554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9235279319bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_department_name'), ['department_name'], unique=True)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('patronimic', sa.String(length=128), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('work_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_patronimic'), ['patronimic'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_salary'), ['salary'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_work_status'), ['work_status'], unique=False)

    op.create_table('departmentEmployee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='fk_department_work_id'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_employee_work_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departmentEmployee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departmentEmployee_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departmentEmployee_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departmentEmployee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departmentEmployee_employee_id'))
        batch_op.drop_index(batch_op.f('ix_departmentEmployee_department_id'))

    op.drop_table('departmentEmployee')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_work_status'))
        batch_op.drop_index(batch_op.f('ix_employees_salary'))
        batch_op.drop_index(batch_op.f('ix_employees_patronimic'))
        batch_op.drop_index(batch_op.f('ix_employees_last_name'))
        batch_op.drop_index(batch_op.f('ix_employees_first_name'))

    op.drop_table('employees')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_department_name'))

    op.drop_table('department')
    # ### end Alembic commands ###
