"""empty message

Revision ID: fca6aeb9e0e1
Revises: 1d96fa657b8c
Create Date: 2024-05-15 16:53:49.613311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca6aeb9e0e1'
down_revision = '1d96fa657b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('ix_employees_working_status')
        batch_op.drop_column('working_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_status', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_employees_working_status', ['working_status'], unique=False)

    # ### end Alembic commands ###
